services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Guard\:
        resource: '../../src/Guard'

    App\Providers\:
        resource: '../../src/Providers'

    App\Action\:
        resource: '../../src/Action'
        public: true

    App\Managers\:
        resource: '../../src/Managers'

    App\Schemas\:
        resource: '../../src/Schemas'
