security:
    encoders:
        App\Model\User:
            algorithm: bcrypt

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/api
            anonymous: null
            #provider: api_token
            guard:
                authenticators:
                    - App\Guard\TokenAuthenticator

