security:
    encoders:
        App\Model\User:
            algorithm: bcrypt

    providers:
        my_mongo_provider:
            mongodb:
                class: App\Model\User
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: null
        # api:
            # pattern: ^/api
            # provider: my_mongo_provider
            # stateless: true
            # guard:
                # authenticator:
                    # - App\Security\TokenAuthenticator

