security:
    encoders:
        App\Model\User:
            algorithm: bcrypt

    providers:
        user_provider:
            mongodb:
                class: App\Model\User
                property: username
        api_token:
            id: App\Providers\ApiTokenUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            anonymous: null
            provider: api_token
            guard:
                authenticators:
                    - App\Guard\TokenAuthenticator

