security:
    encoders:
        App\Model\User:
            algorithm: bcrypt

    providers:
        my_mongo_provider:
            mongodb:
                class: App\Model\User
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: null
        # api:
            # pattern:   ^/api
            # stateless: true
            # provider: my_mongo_provider
            # guard:
                # authenticators:
                    # - App\Guard\TokenAuthenticator

    # access_control:
        # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
