snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
        doctrine:
            type: predis
            alias: doctrine
            dsn: "%env(REDIS_URL)%"
    doctrine:
        query_cache:
             client: doctrine
             document_manager: default
        result_cache:
            client: doctrine
            document_manager: default
