stages:
    - unit_tests

unit_tests:
    stage: unit_tests
    image: php:fpm
    before_script:
        - apt-get update -y
        - apt-get install -y \
                  libfreetype6-dev \
                  libjpeg62-turbo-dev \
                  libmcrypt-dev \
                  libpng12-dev \
                  zip \
                  unzip \
                  wget \
                  curl \
                  libcurl4-openssl-dev \
                  pkg-config \
                  libssl-dev
        - pecl install apcu xdebug mongodb 1.3.1
        - apt-get install -y libpq-dev
        - docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
        - docker-php-ext-install pdo_mysql opcache json pdo_pgsql pgsql 
        - docker-php-ext-enable apcu xdebug mongodb.so
        - apt-get install zip unzip
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
    script:
        - php composer.phar install
        - vendor/bin/phpunit -v
