stages:
    - unit tests
    - functional tests
    - server_config
    - deployment

before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SERVER_PRIVATE_KEY")
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
    stage: test
    image: guikingone/test_env
    before_script:
        - docker-compose up -d --build
    script:
        - echo 'Tests in progress'
