stages:
    - quality
    - frontend
    - unit_tests
    - cloud

insight:
    stage: quality
    image: php:fpm
    before_script:
        - curl -o insight.phar -s http://get.insight.sensiolabs.com/insight.phar
    script:
        - php insight.phar analyze --no-interaction --no-ansi $INSIGHT_PROJECT_ID --reference=$CI_COMMIT_SHA --user-uuid="$INSIGHT_USER_UID" --api-token="$INSIGHT_USER_TOKEN"
    only:
        - master

encore:
    stage: frontend
    image: node
    before_script:
        - yarn install
    script:
        - ./node_modules/.bin/encore dev

unit_tests:
    stage: unit_tests
    image: php:7.1-fpm
    before_script:
        - apt-get update -y
        - apt-get install -y libssl-dev
        - pecl install apcu xdebug
        - apt-get install -y libpq-dev
        - docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
        - docker-php-ext-install pdo_mysql opcache json pdo_pgsql pgsql
        - docker-php-ext-enable apcu xdebug
        - apt-get install zip unzip git -y
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
    script:
        - php composer.phar install
        - vendor/bin/phpunit -v

deployment:
    stage: cloud
    image: google/cloud-sdk
    before_script:
        - apt-get update -y
        - echo $GOOGLE_CLOUD_KEY > /tmp/google_cloud_project_key.json
        - gcloud config set project $GOOGLE_CLOUD_PROJECT
        - gcloud auth activate-service-account --key-file /tmp/google_cloud_project_key.json
    script:
        - echo 'Hello World from Google Cloud !'
    after_script:
            - rm /tmp/google_cloud_project_key.json
