version: "3.1"

services:
    # Core configuration
    debian:
        container_name: debian_docker
        image: debian
        volumes:
            - './:/var/www/smartfact'
        links:
            - nginx
            - php
        restart: always

    nginx:
        container_name: nginx_docker
        image: nginx
        ports:
            - '8080:80'
        volumes:
            - './:/var/www/smartfact'
            - './docker/nginx/conf:/etc/nginx/conf.d:ro'
        restart: always

    php:
        container_name: php_docker
        build: '.'
        volumes:
            - './:/var/www/smartfact'
            - './docker/php/:/usr/local/etc/php'
        depends_on:
            - nginx
        restart: always

    nodejs:
        container_name: node_docker
        image: node
        ports:
            - '9800'
        restart: always

    # Testing configuration
    blackfire:
        container_name: forteroche_blackfire_docker
        image: blackfire/blackfire
        links:
            - php
        restart: always

    # DB configuration
    mongodb:
        container_name: mongodb_docker
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - 'mongo_docker:/data/db'
        restart: always

    postgres:
        container_name: postgres_docker
        image: postgres:latest
        environment:
            POSTGRES_USER: 'docker'
            POSTGRES_PASSWORD: 'docker'
            POSTGRES_DB: 'docker'
        ports:
            - '5432:5432'
        volumes:
            - 'postgres_docker:/var/lib/postgresql/data'
        restart: always

    mysql:
        container_name: mysql_docker
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'docker'
            MYSQL_USER: 'docker'
            MYSQL_PASSWORD: 'docker'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        ports:
            - '3306:3306'
        volumes:
            - 'mysql_docker:/var/lib/mysql'
        restart: always

volumes:
    mongo_docker:
    postgres_docker:
    mysql_docker:
