version: "3.1"

services:
    # Core configuration
    debian:
        container_name: ${CONTAINER_PREFIX}_debian
        image: debian
        volumes:
            - './:/var/www/smartfact'
        links:
            - nginx
            - php
        restart: always

    nginx:
        container_name: ${CONTAINER_PREFIX}_nginx
        image: nginx
        ports:
            - '${NGINX_PORT}:80'
        volumes:
            - './:/var/www/smartfact'
            - './docker/nginx/conf:/etc/nginx/conf.d:ro'
        restart: always

    php:
        container_name: ${CONTAINER_PREFIX}_php
        build: '.'
        volumes:
            - './:/var/www/smartfact'
            - './docker/php/:/usr/local/etc/php'
        restart: always

    nodejs:
        container_name: ${CONTAINER_PREFIX}_node
        image: node
        ports:
            - '${NODE_PORT}'
        restart: always

    # DB configuration
    mongodb:
        container_name: ${CONTAINER_PREFIX}_mongodb
        image: mongo:latest
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            - 'mongo_docker:/data/db'
        restart: always

    postgres:
        container_name: ${CONTAINER_PREFIX}_postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_NAME}'
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - 'postgres_docker:/var/lib/postgresql/data'
        restart: always

    mysql:
        container_name: ${CONTAINER_PREFIX}_mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: '${DB_NAME}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - 'mysql_docker:/var/lib/mysql'
        restart: always

    # Testing configuration
    blackfire:
        container_name: ${CONTAINER_PREFIX}_blackfire
        image: blackfire/blackfire
        links:
            - php
        restart: always

volumes:
    mongo_docker:
    postgres_docker:
    mysql_docker:
