version: "3.1"

services:
    # Core configuration
    debian:
        container_name: ${CONTAINER_PREFIX}_debian
        build: './core'
        volumes:
            - './core:/var/www/smartfact:rw'

    nginx:
        container_name: ${CONTAINER_PREFIX}_nginx
        image: nginx
        ports:
            - '${NGINX_PORT}:80'
        links:
            - debian
        volumes:
            - './core:/var/www/smartfact:rw'
            - './nginx/conf/core/nginx.conf:/etc/nginx/conf/nginx.conf:ro'
            - './nginx/conf/app/:/etc/nginx/conf.d:ro'
            - './nginx/logs/:/var/log/nginx'

    nodejs:
        container_name: ${CONTAINER_PREFIX}_node
        image: node
        ports:
            - '${NODE_PORT}:32793'
        links:
            - debian
        volumes:
            - './core:/var/www/smartfact'

    php-fpm:
        container_name: ${CONTAINER_PREFIX}_php-fpm
        build: './php'
        ports:
            - '${PHP_PORT}:9000'
        links:
            - debian
        volumes:
            - './core:/var/www/smartfact:rw'
            - './docker/php/:/usr/local/etc/php'

    # DB configuration
    mongodb:
        container_name: ${CONTAINER_PREFIX}_mongodb
        image: mongo:latest
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            - 'mongo_docker:/data/db'
        restart: always

    postgres:
        container_name: ${CONTAINER_PREFIX}_postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_NAME}'
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - 'postgres_docker:/var/lib/postgresql/data'
        restart: always

    mysql:
        container_name: ${CONTAINER_PREFIX}_mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: '${DB_NAME}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - 'mysql_docker:/var/lib/mysql'
        restart: always

    # Testing configuration
    blackfire:
        container_name: ${CONTAINER_PREFIX}_blackfire
        image: blackfire/blackfire
        links:
            - debian
        volumes:
            - './core:/var/www/smartfact'
        restart: always

volumes:
    mongo_docker:
    postgres_docker:
    mysql_docker:
