# Users
api_users:
    path:    '/users'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Users\GetUsersAction }

api_user_personnal:
    path:    '/users/me'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Users\GetPersonalUserAction }

api_users_single_post:
    path:    '/users/post'
    methods: ['POST']
    defaults: { _controller: App\Action\Api\Users\PostUserAction }

api_users_single_put:
    path:    '/users/{id}/put'
    methods: ['PUT']
    defaults: { _controller: App\Action\Api\Users\PutUserAction }
    requirements:
        id: '\S+'

api_users_single_patch:
    path:    '/users/{id}/patch'
    methods: ['PATCH']
    defaults: { _controller: App\Action\Api\Users\PatchUserAction }
    requirements:
        id: '\S+'

api_users_single_delete:
    path:    '/users/{id}/delete'
    methods: ['DELETE']
    defaults: { _controller: App\Action\Api\Users\DeleteUserAction }
    requirements:
        id: '\S+'
