# Users
api_users:
    path:    '/users'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Users\GetUsersAction }

api_users_single:
    path:    '/users/{id}'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Users\GetUserAction }

api_users_single_post:
    path:    '/users/post'
    methods: ['POST']
    defaults: { _controller: App\Action\Api\Users\PostUserAction }

api_users_single_put:
    path:    '/users/{id}/put'
    methods: ['PUT']
    defaults: { _controller: App\Action\Api\Users\GetUserAction }

api_users_single_patch:
    path:    '/users/{id}/patch'
    methods: ['PATCH']
    defaults: { _controller: App\Action\Api\Users\GetUserAction }

api_users_single_delete:
    path:    '/users/{id}/delete'
    methods: ['DELETE']
    defaults: { _controller: App\Action\Api\Users\GetUserAction }
