# Clients
api_clients:
    path:    '/clients'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Clients\GetClientsAction }

api_clients_single:
    path:    '/clients/{id}'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Clients\GetClientAction }

api_clients_single_post:
    path:    '/clients/post'
    methods: ['POST']
    defaults: { _controller: App\Action\Api\Clients\PostClientAction }

api_clients_single_put:
    path:    '/clients/{id}/put'
    methods: ['PUT']
    defaults: { _controller: App\Action\Api\Clients\PutClientsAction }

api_clients_single_patch:
    path:    '/clients/{id}/patch'
    methods: ['PATCH']
    defaults: { _controller: App\Action\Api\Clients\PatchClientsAction }

api_clients_single_delete:
    path:    '/clients/{id}/delete'
    methods: ['DELETE']
    defaults: { _controller: App\Action\Api\Clients\DeleteClientsAction }
