# Meetups
api_meetup:
    path:    '/meetups'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Meetups\GetMeetupsAction }

api_meetup_single:
    path:    '/meetups/{id}'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Meetups\GetMeetupAction }
    requirements:
        id: \d+

api_meetup_single_post:
    path:    '/meetups/planning/{id}/post'
    methods: ['POST']
    defaults: { _controller: App\Action\Api\Meetups\PostMeetupsAction }
    requirements:
        id: \d+

api_meetup_single_put:
    path:    '/meetups/{id}/put'
    methods: ['PUT']
    defaults: { _controller: App\Action\Api\Meetups\PutMeetupsAction }
    requirements:
        id: \d+

api_meetup_single_patch:
    path:    '/meetups/{id}/patch'
    methods: ['PATCH']
    defaults: { _controller: App\Action\Api\Meetups\PatchMeetupsAction }
    requirements:
        id: \d+

api_meetup_single_delete:
    path:    '/meetups/{id}/delete'
    methods: ['DELETE']
    defaults: { _controller: App\Action\Api\Meetups\DeleteMeetupsAction }
    requirements:
        id: \d+
