# Notifications
api_notifications:
    path:    '/notifications/users/{id}'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Notifications\GetNotificationsAction }
    requirements:
         id: \d+

api_notifications_single:
    path:    '/notifications/{id}/user/{userId}'
    methods: ['GET']
    defaults: { _controller: App\Action\Api\Notifications\getNotificationAction }
    requirements:
         id: \d+
         userId: \d+

api_notifications_single_post:
    path:    '/notifications/users/{id}/post'
    methods: ['POST']
    defaults: { _controller: App\Action\Api\Notifications\PostNotificationsAction }
    requirements:
         id: \d+

api_notifications_single_put:
    path:    '/notifications/{id}/users/{userId}/put'
    methods: ['PUT']
    defaults: { _controller: App\Action\Api\Notifications\PutNotificationsAction }
    requirements:
         id: \d+
         userId: \d+

api_notifications_single_patch:
    path:    '/notifications/{id}/users/{userId}/patch'
    methods: ['PATCH']
    defaults: { _controller: App\Action\Api\Notifications\PatchNotificationsAction }
    requirements:
         id: \d+
         userId: \d+

api_notifications_single_delete:
    path:    '/notifications/{id}/users/{userId}/delete'
    methods: ['DELETE']
    defaults: { _controller: App\Action\Api\Notifications\DeleteNotificationsAction }
    requirements:
         id: \d+
         userId: \d+
