services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Listeners\:
        resource: '../../src/AppBundle/Listeners'
        tags:
            - { name: kernel.event_listener, event: notifications.posted }
            - { name: kernel.event_listener, event: notifications.deleted }
