app:
    resource: '@AppBundle/Action/Web/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: en|fr

api:
    resource: '@AppBundle/Action/Api/'
    type: annotation
    prefix: /api
