parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Action\:
        resource: '../../src/AppBundle/Action'
        public: true

    AppBundle\Managers\:
        resource: '../../src/AppBundle/Managers'
        public: true
