App\Model\Bills:
    type: entity
    repositoryClass: App\Repository\BillsRepository
    table: _smartfact_bills
    id:
        id:
             type: integer
             generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
            nullable: false
        total:
            type: float
            nullable: false
        send:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            nullable: false
        sendAt:
            type: datetime
            nullable: false
        file:
            type: string
            length: 150
            nullable: false
        tva:
            type: boolean
            nullable: false

    manyToOne:
        user:
            targetEntity: App\Model\User
            inversedBy: bills
        clients:
            targetEntity: App\Model\Clients
            inversedBy: bills
