App\Model\Planning:
    type: entity
    repositoryClass: App\Repository\PlanningRepository
    table: _smartfact_planning
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        period:
            type: string
            length: 10
            nullable: false

    oneToMany:
        meetups:
            targetEntity: App\Model\Meetup
            mappedBy: planning

    oneToOne:
        user:
            targetEntity: App\Model\User
            inversedBy: planning
