Mutation:
    type: object
    config:
        description: ""
        fields:
            registerUser:
                type: "UserInteractor"
                description: "Allow to register a new user."
                args:
                    email:
                        type: "String!"
                        description: "The email of the user."
                    username:
                        type: "String!"
                        description: "The username of the user."
                    password:
                        type: "String!"
                        description: "The password of the user."
                resolve: ""

