Mutation:
    type: object
    config:
        description: ""
        fields:
            createNotification:
                type: "NotificationInteractor"
                description: "Allow to create a new Notification"
                args:
                    label:
                        type: "String!"
                        description: "The label of the Notification."
                    content:
                        type: "String!"
                        description: "The content of the Notification."
                    tags:
                        type: "[String!]"
                        description: "The tags of the Notification."
                resolve: "@=service('app.notification_mutator').createNotification(args)"
            deleteNotification:
                type: "NotificationInteractor"
                description: "Allow to delete a Notification"
                args:
                    id:
                        type: "Int!"
                        description: "The identifier of the Notification."
                resolve: "@=service('app.notification_mutator').deleteNotification(args)"

