Query:
    type: object
    config:
        description: "Allow to query all the entities."
        fields:
            notifications:
                type: "[NotificationInteractor]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the notifications."
                    user_id:
                        type: "Int"
                        description: "The id of the user who own the notification."
                resolve: "@=service('app.notifications_resolver').getNotifications(args)"
