Query:
    type: object
    config:
        description: "Allow to query all the entities."
        fields:
            notification:
                type: "[NotificationInteractor]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of a single notification."
                    tags:
                        type: "String"
                        description: "The tag of the notifications."
                    userId:
                        type: "Int"
                        description: "The id of the user who own the notifications (if a notification id is passed, a single notification is returned)."
                resolve: "@=service('app.notifications_resolver').getNotifications(args)"
            image:
                type: "[ImageInteractor]"
                args:
                    id:
                        type: "Int"
                        description: ""
                    name:
                        type: "String"
                        description: ""
                resolve: "@=service('app.image_resolver').getImages(args)"
            client:
                type: "[ClientInteractor]"
                args:
                    id:
                        type: "Int"
                        description: ""
                    name:
                        type: "String"
                        description: ""
                resolve: "@=service('app.image_resolver').getImages(args)"
            accounting:
                type: "[AccountingInteractor]"
                args:
                    id:
                        type: "Int"
                        description: ""
                    name:
                        type: "String"
                        description: ""
                resolve: "@=service('app.image_resolver').getImages(args)"
            company:
                type: "[CompanyInteractor]"
                args:
                    id:
                        type: "Int"
                        description: ""
                    name:
                        type: "String"
                        description: ""
                resolve: "@=service('app.image_resolver').getImages(args)"
