App\Model\Meetup:
    type: document
    collection: _smartfact_meetup
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        date:
            type: datetime
            nullable: false
        places:
            type: string
            length: 100
            nullable: false
        duration:
            type: string
            length: 125
            nullable: false
        type:
            type: string
            length: 100
            nullable: false

    referenceOne:
        planning:
            targetDocument: App\Model\Planning
            inversedBy: meetups
        user:
            targetDocument: App\Model\User
            inversedBy: meetups
        clients:
            targetDocument: App\Model\Clients
            inversedBy: meetups
