App\Model\User:
    type: document
    collection: _smartfact_user
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        firstname:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 200
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        phoneNumber:
            type: string
            length: 15
            nullable: true
        email:
            type: string
            length: 150
            nullable: false
        birthdate:
            type: date
            nullable: true
        status:
            type: string
            length: 150
            nullable: false
        createdAt:
            type: date
            nullable: false
        validated:
            type: boolean
            nullable: false
        isActive:
            type: boolean
            nullable: false
        username:
            type: string
            length: 100
            nullable: false
        password:
            type: string
            length: 150
            nullable: false
        token:
            type: string
            length: 150
            nullable: false
        roles:
            type: string
            nullable: false
        scope:
            type: string
            nullable: false
        state:
            type: string
            nullable: true

    referenceOne:
        planning:
            targetDocument: App\Model\Planning
            mappedBy: user
        accounting:
            targetDocument: App\Model\Accounting
            inversedBy: users

    referenceMany:
        notifications:
            targetDocument: App\Model\Notifications
            mappedBy: users
        clients:
            targetDocument: App\Model\Clients
            mappedBy: users
        bills:
            targetDocument: App\Model\Bills
            mappedBy: users
        meetups:
            targetDocument: App\Model\Meetup
            mappedBy: users
