# Security
api_token_entrypoint:
    path:    '/token'
    methods: ['POST']
    defaults: { _controller: App\Action\Api\Security\ApiTokenAction }

accounting:
   resource: "routes/accounting/routing_accounting.yaml"

users:
   resource: "routes/users/routing_users.yaml"

