accounting:
   resource: "routes/api/routing_accounting.yaml"

bills:
   resource: "routes/api/routing_bills.yaml"

clients:
   resource: "routes/api/routing_clients.yaml"

meetups:
   resource: "routes/api/routing_meetup.yaml"

notifications:
   resource: "routes/api/routing_notifications.yaml"

planning:
   resource: "routes/api/routing_planning.yaml"

users:
   resource: "routes/api/routing_users.yaml"
