parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Exceptions\Listeners\:
        resource: '../src/Exceptions/Listeners'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Listeners\:
        resource: '../src/Listeners'
        tags:
            - { name: kernel.event_listener, event: bills.created }
            - { name: kernel.event_listener, event: bills.updated }
            - { name: kernel.event_listener, event: bills.deleted }
            - { name: kernel.event_listener, event: notification.deleted }
            - { name: kernel.event_listener, event: users.created }
