parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Providers\:
        resource: '../src/Providers'

    App\Action\:
        resource: '../src/Action'
        tags:
            - 'controller.service_arguments'

    App\Responder\:
        resource: '../src/Responder'

    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags:
            - 'doctrine.fixtures.orm'

    # Resolver
    app.accountings_resolver:
        class: App\Resolver\AccountingResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver }

    app.bills_resolver:
        class: App\Resolver\BillsResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver }

    app.clients_resolver:
        class: App\Resolver\ClientsResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver }

    app.companies_resolver:
        class: App\Resolver\CompanyResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver }

    app.images_resolver:
        class: App\Resolver\ImageResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver }

    app.notifications_resolver:
        class: App\Resolver\NotificationResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver }

    app.products_resolver:
        class: App\Resolver\ProductResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver }

    app.users_resolver:
        class: App\Resolver\UserResolver
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver }

    # Mutators
    app.notifications_mutator:
        class: App\Mutator\NotificationMutator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.mutation }

    App\Managers\:
        resource: '../src/Managers'

    App\Exceptions\Listeners\:
        resource: '../src/Exceptions/Listeners'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Listeners\Users\:
        resource: '../src/Listeners/Users'
        tags:
            - { name: kernel.event_listener, event: users.created }
            - { name: kernel.event_listener, event: users.updated }

    App\Listeners\Bills\:
        resource: '../src/Listeners/Bills'
        tags:
            - { name: kernel.event_listener, event: bills.created }
            - { name: kernel.event_listener, event: bills.updated }
            - { name: kernel.event_listener, event: bills.deleted }

    App\Listeners\Notifications\:
        resource: '../src/Listeners/Notifications'
        tags:
            - { name: kernel.event_listener, event: notifications.deleted }
