AppBundle\Entity\Clients:
    attributes:
        id:
            groups: ['users', 'clients', 'bills', 'meetup']
        name:
            groups: ['users', 'clients', 'bills', 'meetup']
        address:
            groups: ['users', 'clients', 'bills', 'meetup']
        phoneNumber:
            groups: ['users', 'clients', 'bills', 'meetup']
        prestationType:
            groups: ['users', 'clients', 'bills', 'meetup']
        user:
            groups: ['clients', 'bills', 'meetup']
        bills:
            groups: ['users', 'clients', 'meetup']
        meetup:
            groups: ['users', 'clients', 'bills']
