AppBundle\Entity\Planning:
    attributes:
        id:
            groups: ['users', 'planning', 'meetup']
        period:
            groups: ['users', 'planning', 'meetup']
        meetup:
            groups: ['users', 'planning']
        user:
            groups: ['planning', 'meetup']
