api_register_entrypoint:
    path:    '/api/register'
    methods: ['POST']
    defaults: { _controller: App\Action\Security\ApiRegisterUserAction }

api_oauth_entrypoint:
    path: '/oauth2/token'
    methods: ['POST']
    defaults: { _controller: App\Action\Security\ApiOauthAction }

api_jwt_entrypoint:
    path:    '/jwt/token'
    methods: ['POST']
    defaults: { _controller: App\Action\Security\ApiTokenAction }

api_forgot_password_entrypoint:
    path:    '/api/forgot/password'
    methods: ['POST']
    defaults: { _controller: App\Action\Api\Users\PostUserAction }

register:
    path:    '/register'
    methods: ['GET', 'POST']
    defaults: { _controller: App\Action\Security\RegisterAction }

login:
    path:    '/login'
    methods: ['GET', 'POST']
    defaults: { _controller: App\Action\Security\LoginAction }
