App\Entity\Meetup:
    attributes:
        id:
            groups: ['users', 'planning', 'clients']
        dates:
            groups: ['users', 'planning', 'clients']
        places:
            groups: ['users', 'planning', 'clients']
        duration:
            groups: ['users', 'planning', 'clients']
        type:
            groups: ['users', 'planning', 'clients']
        user:
            groups: ['planning', 'clients']
        planning:
            groups: ['users', 'clients']
        clients:
            groups: ['users', 'planning']
