App\Entity\User:
    attributes:
        id:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        firstname:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        lastname:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        address:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        phoneNumber:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        email:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        birthdate:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        status:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        createdAt:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        validated:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        isActive:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        username:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        roles:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        notifications:
            groups: ['users', 'planning', 'accounting', 'bills', 'clients', 'meetup']
        clients:
            groups: ['users', 'notifications', 'planning', 'accounting', 'bills', 'meetup']
        accounting:
            groups: ['users', 'notifications', 'planning', 'bills', 'clients', 'meetup']
        bills:
            groups: ['users', 'notifications', 'planning', 'accounting', 'clients', 'meetup']
        planning:
            groups: ['users', 'notifications', 'accounting', 'bills', 'clients', 'meetup']
