App\Model\Meetup:
    type: entity
    repositoryClass: App\Repository\MeetupRepository
    table: _smartfact_meetup
    id:
         id:
             generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
            nullable: false
        places:
            type: string
            length: 100
            nullable: false
        duration:
            type: string
            length: 125
            nullable: false
        type:
            type: string
            length: 100
            nullable: false

    manyToOne:
        planning:
            targetEntity: App\Model\Planning
            inversedBy: meetups
        user:
            targetEntity: App\Model\User
            inversedBy: meetups
        clients:
            targetEntity: App\Model\Clients
            inversedBy: meetups
