App\Model\Notifications:
    type: entity
    repositoryClass: App\Repository\NotificationsRepository
    table: _smartfact_notifications
    id:
        id:
            type: integer
            generated: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 50
            nullable: false
        category:
            type: string
            length: 50
            nullable: false
        createdAt:
            type: datetime
            nullable: false
        link:
            type: string
            length: 200
            nullable: false
        content:
            type: string
            length: 255
            nullable: false
        repetition:
            type: boolean
            nullable: false
        checked:
            type: boolean
            nullable: false

    manyToOne:
        user:
             targetEntity: App\Model\User
             mappedBy: notifications
