App\Interactors\AccountingInteractor:
    type: entity
    table: smartfact_accounting
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 150
            unique: true
        interlocutor:
            type: string
            length: 150
            nullable: true
            unique: true
        phoneNumber:
            type: string
            length: 20
            nullable: true
            unique: true
        email:
            type: string
            length: 200
            unique: true
        address:
            type: string
            length: 255

    oneToOne:
        company:
            targetEntity: App\Interactors\CompanyInteractor
            mappedBy: accounting
            cascade: ['persist']
