App\Interactors\ClientInteractor:
    type: entity
    table: smartfact_client
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 200
            nullable: false
            unique: true
        firstName:
            type: string
            length: 100
            nullable: true
        lastName:
            type: string
            length: 100
            nullable: true
        legalIdentifier:
            type: string
            length: 20
            nullable: false
            unique: true
        taxesIdentifier:
            type: string
            length: 30
            nullable: false
            unique: true
        artisanIdentifier:
            type: string
            length: 200
            nullable: true
            unique: true
        format:
            type: string
            length: 15
            nullable: false
            unique: true
        address:
            type: string
            length: 255
            nullable: false
            unique: true
        socialAddress:
            type: string
            length: 255
            nullable: false
            unique: true

    oneToOne:
        image:
            targetEntity: App\Interactors\ImageInteractor
            inversedBy: client
            joinColumn:
                name: image_id
                referencedColumnName: id

    oneToMany:
        bills:
            targetEntity: App\Interactors\BillsInteractor
            mappedBy: client
            cascade: ['persist']

    manyToOne:
        recipient:
            targetEntity: App\Interactors\CompanyInteractor
            inversedBy: clients
            joinColumn:
                name: recipient_id
                referencedColumnName: id
