App\Interactors\ImageInteractor:
    type: entity
    table: smartfact_image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:

    oneToOne:
        client:
            targetEntity: App\Interactors\ClientInteractor
            mappedBy: image
            cascade: ['persist']
        company:
            targetEntity: App\Interactors\CompanyInteractor
            mappedBy: image
            cascade: ['persist']
