App\Interactors\NotificationInteractor:
    type: entity
    table: smartfact_notification
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        label:
            type: string
            length: 100
            unique: true
        content:
            type: string
            length: 150
            nullable: true
            unique: true
        tags:
            type: string
            length: 20
            nullable: true
            unique: true

    manyToOne:
        user:
            targetEntity: App\Interactors\UserInteractor
            inversedBy: notifications
            joinColumn:
                name: user_id
                referencedColumnName: id
