App\Interactors\ProductInteractor:
    type: entity
    table: smartfact_product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 200
            nullable: false
        price:
            type: float
            nullable: false
        quantity:
            type: float
            nullable: false

    manyToOne:
        bill:
            targetEntity: App\Interactors\BillsInteractor
            inversedBy: products
            joinColumn:
                name: bill_id
                referencedColumnName: id
