App\Interactors\ProductInteractor:
    type: entity
    table: smartfact_product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:

    manyToOne:
        bill:
            targetEntity: App\Interactors\BillsInteractor
            inversedBy: products
            joinColumn:
                name: bill_id
                referencedColumnName: id
