App\Interactors\UserInteractor:
    type: entity
    table: smartfact_user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstName:
            type: string
            length: 75
            nullable: true
        lastName:
            type: string
            length: 100
            nullable: true
        username:
            type: string
            nullable: false
            unique: true
        email:
            type: string
            nullable: false
            unique: true
        password:
            type: string
            length: 200
            nullable: false
        roles:
            type: array
            nullable: false
        creationDate:
            type: datetime
            nullable: false
        validationDate:
            type: datetime
            nullable: true
        validationToken:
            type: string
            length: 255
            nullable: true
        validated:
            type: boolean
            nullable: false
        active:
            type: boolean
            nullable: false
        resetToken:
            type: string
            length: 155
            nullable: true
            unique: true
        apiToken:
            type: string
            length: 350
            nullable: true
            unique: true

    oneToOne:
        image:
            targetEntity: App\Interactors\ImageInteractor
            inversedBy: user
            joinColumn:
                name: image_id
                referencedColumnName: id

    oneToMany:
        company:
            targetEntity: App\Interactors\CompanyInteractor
            mappedBy: owner
            cascade: ['persist', 'remove']

        notifications:
            targetEntity: App\Interactors\NotificationInteractor
            mappedBy: user
            cascade: ['remove']
